[book]
authors = ["Koh Wei Jie"]
language = "en"
multilingual = false
src = "src"
title = "clientside"

#[output.katex]

[preprocessor.katex]
after = ["links"]
#renderers = ["html"]
#inline-delimiter = {left = "\\(", right = "\\)"}

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
